branch-defaults:
  master:
    environment: nest-hello-world-dev
    group_suffix: null
environment-defaults:
  nest-hello-world-dev:
    branch: null
    repository: null
global:
  application_name: nest-hello-world
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Node.js 18 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
